# Generated by Django 3.0.8 on 2020-08-04 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.CharField(max_length=1000, verbose_name='내용')),
                ('writer', models.CharField(max_length=30, verbose_name='작성자')),
                ('write_date', models.DateTimeField(default=datetime.datetime(2020, 8, 4, 9, 56, 31, 873917), verbose_name='작성일자')),
                ('click_num', models.IntegerField(default=0, verbose_name='조회수')),
                ('like_num', models.IntegerField(default=0, verbose_name='좋아요')),
                ('unlike_num', models.IntegerField(default=0, verbose_name='싫어요')),
            ],
        ),
    ]
